---

- name: cluster | Check clluster status for all the nodes except the node to join with
  shell: "rabbitmqctl cluster_status | grep {{ rabbitmq_cluster_instance_to_join }}"
  changed_when: False
  ignore_errors: True
  when: "{{ rabbitmq_cluster_instance_to_join !=  ansible_fqdn }}"
  register: cluster_result

- name: cluster | stop rabbitmq app for standalone nodes in order to join
  shell: "rabbitmqctl stop_app"
  when: cluster_result is defined and cluster_result.rc == 1

# for this to work, an entry including the short hostname must exist in /etc/hosts
- name: cluster | add this node to cluster
  shell: "rabbitmqctl join_cluster rabbit@{{ rabbitmq_cluster_instance_to_join }}"
  when: cluster_result is defined and cluster_result.rc == 1

- name: cluster | start rabbitmq app for standalone nodes
  shell: "rabbitmqctl start_app"
  when: cluster_result is defined and cluster_result.rc == 1
