---

- include: hostnames.yml
  when: rabbitmq_clustering

- include: install/main.yml

- include: configuration.yml

- include: plugins.yml

- include: vhost.yml

- include: policy.yml
  when: "rabbitmq_policy_configuration is defined"

- include: federation.yml
  when: rabbitmq_federation

- include: erlang_cookie.yml
  when: rabbitmq_clustering
  tags: ["rabbitmq-erlang"]

- include: cluster.yml
  when: rabbitmq_clustering
  tags: ["rabbitmq-cluster"]
